In [ ]:
!pip install pymp-pypi

In [ ]:
!pip install numba

In [ ]:
import random
import numpy as np
tim = []

n = int(input())
mat = np.random.randint(low = 0, high = 100, size = (n,n))
new_mat = np.random.randint(low = 0, high = 1, size = (n,n))
import time
start = time.time()
for i in range(n):
  for j in range(n):
    for k in range(n):
      new_mat[i][j]+= mat[i][k]*mat[k][j]
end = time.time()
tim.append(end-start)
print("Old Matrix")
print(mat)
print("New Matrix")
print(new_mat)

5
Old Matrix
[[ 0  4 71 94 38]
 [14 25 63 14 36]
 [47 84 74 18 85]
 [58 84 39 17 52]
 [99 48  8 95 79]]
New Matrix
[[12607 15784  9476  6542 14069]
 [ 7687  8877  8065  6458 10359]
 [14113 14096 15487 15307 18751]
 [ 9143  9532 13375 12559 13535]
 [14379 14040 14982 19242 17351]]


Parallel

In [ ]:
from threading import Thread
def multiply(a,b, mat, new_mat):
  for i in range(a,b):
    for j in range(n):
      for k in range(n):
        new_mat[i][j]+= mat[i][k]*mat[k][j]
threads = [None] * (n)
start = time.time()
for i in range(len(threads)):
    threads[i] = Thread(target=multiply, args=(i,i+1,mat,new_mat))
    threads[i].start()

for i in range(len(threads)):
    threads[i].join()

# print
end = time.time()
tim.append(end-start)
print(new_mat)

[[25214 31568 18952 13084 28138]
 [15374 17754 16130 12916 20718]
 [28226 28192 30974 30614 37502]
 [18286 19064 26750 25118 27070]
 [28758 28080 29964 38484 34702]]


## 3. Numpy

In [ ]:
import random
import numpy as np
n = int(input())
mat = np.random.randint(low = 0, high = 100, size = (n,n))
start = time.time()
new_mat = np.matmul(np.matrix(mat),np.matrix(mat))
end = time.time()
print(new_mat)
tim.append(end-start)
print(end-start)

5
[[20340 13246 13108 11382 19251]
 [15419 10881 10988  8207 16840]
 [20976 12639 15715 13118 19796]
 [10483  8604  7955  8092 13103]
 [15507 11979 11942  9922 18929]]
0.00026488304138183594


# 4. Scipy

In [ ]:
import scipy
start = time.time()
new_mat = mat.dot(mat)
end = time.time()
print(new_mat)
tim.append(end-start)
print(end-start)

[[20340 13246 13108 11382 19251]
 [15419 10881 10988  8207 16840]
 [20976 12639 15715 13118 19796]
 [10483  8604  7955  8092 13103]
 [15507 11979 11942  9922 18929]]
6.651878356933594e-05


# Pandas

In [ ]:
import pandas as pd
data1 = pd.DataFrame(data=mat)
data2 = pd.DataFrame(data=mat)
start = time.time()
new_mat = data1.dot(data2)

end = time.time()
print(new_mat)
tim.append(end-start)
print(end-start)

       0      1      2      3      4
0  20340  13246  13108  11382  19251
1  15419  10881  10988   8207  16840
2  20976  12639  15715  13118  19796
3  10483   8604   7955   8092  13103
4  15507  11979  11942   9922  18929
0.000335693359375


# 6. Sympy

In [ ]:
from sympy.matrices import Matrix
from sympy.interactive.printing import init_printing
init_printing(use_unicode=True)
matri = Matrix(mat)
start = time.time()
new_mat = matri*matri
end = time.time()
print(new_mat)
tim.append(end-start)
print(end-start)

Matrix([[20340, 13246, 13108, 11382, 19251], [15419, 10881, 10988, 8207, 16840], [20976, 12639, 15715, 13118, 19796], [10483, 8604, 7955, 8092, 13103], [15507, 11979, 11942, 9922, 18929]])
0.0010039806365966797
